### ISSUE TITLE
About ./data/image_emb_RSICD_aug_center_crop_only.h5 file

### ISSUE THREAD

**Issue by jingzhang697** [comrados/duch#1]
Hello,
    The file cannot be downloaded.Can you help me and give other links?

**Comment by comrados** [comment]
Unfrotunately, I'm not having an access to the file storage.

Seems there's a problem with the file server.

You can create your own embedding files with `./images_augment.py` Same, for the text embeddings there are `./captions_augment.py` and `./captions_embed.py`
